/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthActivityLog {
  activity: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  user_id: string;
}

export interface AuthSession {
  created_at: Generated<Timestamp>;
  expired_at: Timestamp;
  id: Generated<number>;
  last_used_at: Generated<Timestamp>;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface AuthUserProfiles {
  avatar_url: string | null;
  bio: string | null;
  display_name: string | null;
  timezone: string | null;
  user_id: string;
}1

export interface AuthUserProfiles {
  avatar_url: string | null;
  bio: string | null;
  display_name: string | null;
  timezone: string | null;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  password_hash: string;
  status: Generated<'active' | 'offline'>;
  username: string;
}

export interface ChatAttachments {
  file_name: string;
  file_size: Int8;
  file_url: string;
  id: Generated<Int8>;
  message_id: Int8;
  mime_type: string;
}

export interface ChatChannelReadMarkers {
  channel_id: Int8;
  last_read_at: Generated<Timestamp>;
  last_read_message_id: Int8 | null;
  user_id: string;
}

export interface ChatMentions {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  mentioned_user_id: string;
  message_id: Int8;
}

export interface ChatMessagePins {
  id: Generated<Int8>;
  message_id: Int8;
  pinned_at: Generated<Timestamp>;
  pinned_by: string;
}

export interface ChatMessageReadReceipts {
  message_id: Int8;
  seen_at: Generated<Timestamp>;
  user_id: string;
}

export interface ChatMessages {
  channel_id: Int8;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  is_deleted: Generated<boolean>;
  is_edited: Generated<boolean>;
  parent_id: Int8 | null;
  sender_id: string;
}

export interface ChatMessageTags {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  message_id: Int8;
  tag: string;
}

export interface ChatReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<Int8>;
  message_id: Int8;
  user_id: string;
}

export interface ChatTypingIndicators {
  channel_id: Int8;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  user_id: string;
}

export interface ChatUserChatMessages {
  channel_id: Int8 | null;
  content: string | null;
  created_at: Timestamp | null;
  id: Int8 | null;
  is_deleted: boolean | null;
  is_edited: boolean | null;
  parent_id: Int8 | null;
  sender_id: string | null;
  username: string | null;
}

export interface DocsPageBlocks {
  content: Json;
  id: Generated<string>;
  page_id: string;
  position: number;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface DocsPages {
  channel_id: Int8;
  created_at: Generated<Timestamp>;
  created_by: string;
  icon: string | null;
  id: Generated<string>;
  parent_id: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface NotificationsDeliveries {
  delivered_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<string>;
  read_at: Timestamp | null;
  recipient_user_id: string;
  seen_at: Timestamp | null;
  status: Generated<string>;
}

export interface NotificationsEvents {
  actor_user_id: string | null;
  channel: Generated<string>;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  event_type: string;
  id: Generated<string>;
  payload: Generated<Json>;
  payload_version: Generated<number>;
  workspace_id: string | null;
}

export interface TasksTasks {
  assigned_to: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  due_date: Timestamp | null;
  id: Generated<Int8>;
  status: string;
  title: string;
  workspace_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
}

export interface WorkspacesChannels {
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  workspace_id: string;
}

export interface WorkspacesWorkspaceInvitations {
  accepted_at: Timestamp | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by_user_id: string | null;
  invited_user_id: string | null;
  responded_at: Timestamp | null;
  responded_by_user_id: string | null;
  response: string | null;
  role: string;
  status: Generated<string>;
  token_hash: string;
  workspace_id: string;
}

export interface WorkspacesWorkspaceMembers {
  id: Generated<Int8>;
  invited_by_user_id: string | null;
  job_title: string | null;
  joined_at: Generated<Timestamp>;
  member_id: string;
  role: string;
  workspace_display_name: string | null;
  workspace_id: string;
}

export interface WorkspacesWorkspaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: Generated<string>;
  owner_id: string;
  slug: string;
}

export interface DB {
  'auth.activity_log': AuthActivityLog;
  'auth.session': AuthSession;
  "auth.user_profiles": AuthUserProfiles;
  'auth.users': AuthUsers;
  'chat.attachments': ChatAttachments;
  'chat.channel_read_markers': ChatChannelReadMarkers;
  'chat.mentions': ChatMentions;
  'chat.message_pins': ChatMessagePins;
  'chat.message_read_receipts': ChatMessageReadReceipts;
  'chat.message_tags': ChatMessageTags;
  'chat.messages': ChatMessages;
  'chat.reactions': ChatReactions;
  "chat.typing_indicators": ChatTypingIndicators;
  'chat.user_chat_messages': ChatUserChatMessages;
  'docs.page_blocks': DocsPageBlocks;
  'docs.pages': DocsPages;
  'notifications.deliveries': NotificationsDeliveries;
  'notifications.events': NotificationsEvents;
  'tasks.tasks': TasksTasks;
  users: Users;
  "workspaces.channels": WorkspacesChannels;
  "workspaces.workspace_invitations": WorkspacesWorkspaceInvitations;
  "workspaces.workspace_members": WorkspacesWorkspaceMembers;
  "workspaces.workspaces": WorkspacesWorkspaces;
}
